### PR TITLE
fix fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As outlined in the RFP. I also ran `optipng` over the images, reducing them in size without reducing the image quality.

### CODE REVIEW

**Comment by Groomiac** [comment]
That did not seem to help. I got the error from F-Droid:

[](mailbox:///E:/FH2/FH2/Mails/Mail/Local%20Folders/Inbox.sbd/Groomiac?number=2296#uses-permission-and-uses-permission-sdk-23-from-apk)[](mailbox:///E:/FH2/FH2/Mails/Mail/Local%20Folders/Inbox.sbd/Groomiac?number=2296#links-to-services)Fastlane
Error!
Fastlane was not found in your repo!
Without Fastlane, it is not possible to have app screenshots and the app description cannot be updated without going through the F-Droid team, causing unnecessary delays.
It is very strongly recommended to establish Fastlane in your repo.
uses-permission and uses-permission-sdk-23 from APK
groomiac.voicemailplayer_13.apk
Links to Services
by Application ID
by APK

Could you please assist?

**Comment by IzzySoft** [comment]
There's a tag, so that will be used to scan the repo. Fastlane was added after the last tag was created. Could that be? Because I don't see any fastlane [at the latest tag](https://github.com/Groomiac/voicemailplayer/tree/v13).

**Comment by Groomiac** [comment]
Ah ok. Done now. I think...

**Comment by IzzySoft** [comment]
And you've closed [the RFP](https://gitlab.com/fdroid/rfp/-/issues/1936), so the bot will never find out :wink: If that was an accident, please reopen and give me a ping from there, so I can kick the bot again.

**Comment by IzzySoft** [comment]
@Groomiac any chance you could at least add the APK to the last tag?

**Comment by Groomiac** [comment]
> @Groomiac any chance you could at least add the APK to the last tag?

Where exactly? I gave up because I don't know what else to do.

**Comment by IzzySoft** [comment]
[Here](https://github.com/Groomiac/voicemailplayer/releases/tag/v13_w_fastlane_fdroid), then the updater for my repo would pick it up (you know your app is [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/groomiac.voicemailplayer), right?) – Ah, wait: There is a new tag,  but it's basically the same version as the last tag just with Fastlane added? The of course it makes no sense to add the same APK again :see_no_evil: Maybe instead we re-open the RFP and send the bot for another scan – so we get Voice Mail Player to F-Droid.org?

**Comment by Groomiac** [comment]
Done. No, for whatever reason I have no clue what's going on.

**Comment by IzzySoft** [comment]
Thanks! I've triggered the bot again. This time it will find the license and Fastlane, so we hopefully can get to the next step to get the app to F-Droid.org.

**Pull request merged**
